config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'mirrors#index'

  resources :mirrors, only: %i[show index] do
    resource :mirror_calculations, only: %i[show update]
  end

  resources :order_items
  resources :orders, only: %i[index show]
  resource :carts, only: %i[show edit update]
  resource :delivery, only: %i[new create edit update], path: '/order/delivery'
  resources :users, only: %i[new create]
  resource :user, only: %i[edit update]
  resource :session, only: %i[new create destroy]

  namespace :admin do
    resources :mirrors, except: %i[show index] do
      resource :mirror_images, only: [:destroy]
    end

    resources :users, only: %i[index show new create edit update]

    resources :order, only: %i[index show edit update] do
      resources :order_items, only: %i[edit update destroy]
      resource :delivery, only: %i[edit update]
    end

    resource :informations, only: %i[edit update]
  end

  get '/delivery_information', to: 'informations#delivery_information', as: :delivery_information
  get '/company_information', to: 'informations#company_information', as: :company_information
  get '/contact_information', to: 'informations#contact_information', as: :contact_information
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_items
  has_one :delivery
  belongs_to :user
  before_save :set_total_price

  VALID_STATUS = ['in progress', 'confirmed', 'waiting for payment', 'paid', 'delivered', 'canceled'].freeze
  validates :status, inclusion: { in: VALID_STATUS }

  scope :filter_status, ->(value) {
  if ['in progress', 'confirmed', 'waiting for payment', 'paid', 'delivered', 'canceled'].include?(value)
    where(status: value)
  else
    all
  end
}

  scope :with_field_order, lambda { |field = nil, focus = nil|
                             allowed_fields = ['updated_at']
                             field = nil if allowed_fields.exclude?(field)

                             direction = focus == 'desc' ? 'desc' : 'asc'

                             order(field => direction) if field
                           }

  scope :find_by_user_phone, ->(value) { joins(:user).where(users: { phone_number: value }) unless value.blank? }

  def total_price
    order_items.includes(:mirror).map { |order_item| order_item.valid? ? successful_order_item(order_item) : 0 }.sum
  end

  private

  def set_total_price
    self.total_price = total_price
  end

  def successful_order_item(order_item)
    order_item.unit_price * order_item.quantity
  end
end

app/controllers/admin/order_controller.rb
# frozen_string_literal: true

module Admin
  class OrderController < ApplicationController
    include Authentication
    include Admin::Concerns::AdminAuthentication

    before_action :no_authentication
    before_action :check_admin

    def index
      @orders = Order.includes(order_items: :mirror)
                     .filter_status(params[:status])
                     .with_field_order(*params[:focus].to_s.split('-'))
                     .find_by_user_phone(params[:phone_number])
    end

    def edit
      @order = Order.includes(order_items: {
                                mirror: {
                                  mirror_images_attachments: {
                                    blob: :variant_records
                                  }
                                }
                              }).find(params[:id])
      @order_items = @order.order_items
      @delivery = @order.delivery
    end

    def update
      @order = Order.includes(order_items: :mirror).find(params[:id])

      if @order.update(order_params)
        redirect_to edit_admin_order_path(@order)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def order_params
      params.require(:order).permit(:status)
    end
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  include Authentication
  before_action :no_authentication
  
  def index
    @orders=current_user.orders.includes(:order_items => :mirror)
    .filter_status(params[:status])
    .with_field_order(*params[:focus].to_s.split('-'))
  end

  def show
    @order_items = current_order.order_items.includes(mirror: [mirror_images_attachments: :blob])
    @delivery = current_order.delivery
  end

  def show_order
    @order = Order.includes(:order_items => :mirror).find(params[:id])
    @order_items = @order.order_items
    @delivery = @order.delivery
  end

  def order_verification
   current_order
    if @order.order_items.empty?
      redirect_to mirrors_path
      flash[:warning] = 'Your cart is empty. Please add items to your cart before proceeding.'
    else
    @order_items = current_order.order_items.includes(mirror: [mirror_images_attachments: :blob])
    @delivery = current_order.delivery
  end
  end

  def order_confirm
    current_order.update(status: 'confirmed')
    session.delete(:order_id)
    flash[:success] = 'Thank you for your order. We will contact you shortly'
    redirect_to mirrors_path
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  include Authentication
  before_action :no_authentication

  def index
    @orders = current_user.orders.includes(order_items: :mirror)
                          .filter_status(params[:status])
                          .with_field_order(*params[:focus].to_s.split('-'))
  end

  def show
    @order = Order.includes(order_items: :mirror).find(params[:id])
    @order_items = @order.order_items
    @delivery = @order.delivery
  end
end

app/views/order/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 border border-info border-top-0 border-bottom-0 mt-2">
      <%= form_with(model: @order, url: orders_path, method: 'get') do |form| %>
        <div class="border-bottom border-info">
          <p>Status</p>

          <p><%= form.radio_button :status, '', onchange: 'this.form.submit();' %> 
          <%= form.label :status, 'All'%></p>

          <p><%= form.radio_button :status, 'in progress', checked: params[:status] == 'in progress', onchange: 'this.form.submit();' %>
          <%= form.label :status, "In progress" %></p>

          <p><%= form.radio_button :status, 'confirmed', checked: params[:status] == 'confirmed', onchange: 'this.form.submit();' %>
          <%= form.label :status, "Confirmed" %></p>

          <p><%= form.radio_button :status, 'waiting for payment', checked: params[:status] == 'waiting for payment', onchange: 'this.form.submit();' %>
          <%= form.label :status, "Waiting for payment" %></p>

          <p><%= form.radio_button :status, 'paid', checked: params[:status] == 'paid', onchange: 'this.form.submit();' %>
          <%= form.label :status, "Paid" %></p>

          <p><%= form.radio_button :status, 'delivered', checked: params[:status] == 'delivered', onchange: 'this.form.submit();' %>
          <%= form.label :status, "Delivered" %></p>

          <p><%= form.radio_button :status, 'canceled', checked: params[:status] == 'canceled', onchange: 'this.form.submit();' %>
          <%= form.label :status, "Canceled" %></p>
        </div>

        <div class="border-bottom border-info">
          <p>Sort by</p>

          <p><%= form.radio_button :focus, '', checked: params[:focus] == '', onchange: 'this.form.submit();' %> 
          <%= form.label :focus, 'Recommended'%></p>
     
          <p><%= form.radio_button :focus, 'updated_at-desc', checked: params[:focus] == 'updated_at-desc', onchange: 'this.form.submit();' %> 
          <%= form.label :focus, 'Update (New-Old)'%></p>

          <p><%= form.radio_button :focus, 'updated_at-asc', checked: params[:focus] == 'updated_at-asc', onchange: 'this.form.submit();' %> 
          <%= form.label :focus, 'Update (Old-New)'%></p>
        </div>

      <% end %>
    </div>
    <div class="col-md-10 mt-2">
     <table class="table table-bordered border-info">
        <thead>
          <tr>
          <th>Order number</th>
            <th>Total price</th>
            <th>Status</th>
            <th>Updated at</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
            <td><%= order.id %></td>
              <td><%= order.total_price %> $</td>
              <td><%= order.status %></td>
              <td><%= order.updated_at.strftime('%d-%m-%Y') %></td>
              <td><%= link_to 'The order information', show_order_path(order), class: 'btn btn-sm bg-info rounded-0' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/order/order_verification.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9" >
      <% @order_items.each do |order_item| %>
        <div class="card border border-info border-top-0 rounded-0">
          <div class="card-body px-5">
            <div class="row">
              <div class="col-md-4 mt-2">
                <% if order_item.mirror.mirror_images.attached?%>
                  <%= image_tag order_item.mirror.mirror_images.first.variant(resize_to_limit: [300, 250]).processed  %>
                <% end%>
              </div>

              <div class="col-md-4 mt-2" >
                <p> <%= order_item.mirror.name %> </p>
                <p> Height <%= order_item.height %> mm </p>
                <p> Width <%= order_item.width %> mm </p>
                <p> Glass thickness <%= order_item.glass_thickness %> mm </p>
                <p> <%= order_item.light.capitalize %> light  </p>
                <p> <%= order_item.heater == true ? "With heater" : "Without heater" %> </p>
              </div>

              <div class="col-md-3 mt-2" >
                <p> Unit price: <%= order_item.unit_price %> $</p>
                <p> Quantity: <%= order_item.quantity %> </p>
              </div>
            </div>
          </div>
        </div>  
      <% end %>
    </div>
    
    <div class="col-md-3" >
      <p class="fw-bold text-end mx-5 my-3">Total price <%= current_order.total_price %>$</p>
               
      <div class="d-flex justify-content-end mx-5">
        <%= link_to "Edit the order", order_path, class: 'btn bg-info rounded-0'%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <p class="fs-4"> Delivery information</p>

      <%if @delivery.delivery_type == 'Delivery to the post office'%>
        <p> <%= @delivery.delivery_type %> 
            <%= @delivery.post %>
            number <%= @delivery.post_office_number %>
            in <%= @delivery.city %>,
            <%= @delivery.region %> region
        </p>
        <p> Receiver:
          <%= @delivery.receiver_name %>
          <%= @delivery.receiver_surname %> 
        </p>
        <p> Receiver phone number:
          <%= @delivery.receiver_phone_number %> </p>
      <%else%>
        <p> Delivery by 
          <%= @delivery.post %> 
          courier to the address of
          <%= @delivery.region %> region, 
          <%= @delivery.city %>, 
          <%= @delivery.receiver_address %>  
        </p>
        <p> Receiver:
          <%= @delivery.receiver_name %>
          <%= @delivery.receiver_surname %> 
        </p>
        <p> Receiver phone number:
          <%= @delivery.receiver_phone_number %> </p>
      <% end %>

      <p> <%= link_to "Edit delivery information", edit_delivery_path, class: 'btn bg-info rounded-0'%> </p>
    </div>
    <div class="col-md-6">
      <p class="fs-4"> Buyer Information </p>
      <p> Buyer name:
      <%= @user.name %> </p>
      <p> Buyer phone number:
      <%= @user.phone_number %> </p>

      <p><%= link_to "Edit buyer information", edit_user_path(redirect: order_verification_path), class: 'btn bg-info rounded-0' %></p>
    </div>
  </div>
  <p> <%= button_to 'Confirm the order', order_confirm_path, method: :post, class: 'btn btn-dark rounded-0' %> </p>
</div>

app/views/order/show.html.erb
<div class="container-fluid">
  <% if current_order.order_items.size == 0 %>
    <p class="fs-4"> Your cart is empty </p>
  <% else %>
    <div class="row">
      <div class="col-md-9" >
        <% @order_items.each do |order_item| %>
          <div class="card border border-info border-top-0 rounded-0">
            <div class="card-body px-5">
              <div class="row">
                <div class="col-md-4 mt-2">
                  <% if order_item.mirror.mirror_images.attached?%>
                    <%= image_tag order_item.mirror.mirror_images.first.variant(resize_to_limit: [300, 250]).processed  %>
                  <%end%>
                </div>

                <div class="col-md-4 mt-2" >
                  <p> <%= order_item.mirror.name %> </p>

                  <%= form_with model: order_item do |form| %>

                    <p><%= form.label :height %>
                    <%= form.select :height, [50, 80, 100], {}, { onchange: 'this.form.submit();' }  %> 
                    <%= form.submit type: :hidden %></p>

                    <p><%= form.label :width %>
                    <%= form.select :width, [50, 80], {}, { onchange: 'this.form.submit();' }  %> 
                    <%= form.submit type: :hidden %></p>

                    <p><%= form.label :glass_thickness %>
                    <%= form.select :glass_thickness, [4, 6], {}, { onchange: 'this.form.submit();' } %>
                    <%= form.submit type: :hidden %></p>

                    <p><%= form.label :light %> 
                    <%= form.select :light, ['warm', 'neutral', 'cold'], {}, { onchange: 'this.form.submit();' } %> 

                    <p><%= form.label :heater %>
                    <%= form.check_box :heater, { onchange: 'this.form.submit();' } %> 
                    <%= form.submit type: :hidden %></p>

                  <% end %>

                </div>

                <div class="col-md-3 mt-2" >
                  <%= form_with model: order_item do |form| %>
                    <p><%= form.hidden_field :mirror_id, value: order_item.mirror.id %> 
                    Quantity <%= form.number_field :quantity, in: 1.0..20.0, step: 1, value: order_item.quantity %>
                    <%= form.submit "Update", class: 'btn bg-info rounded-0' %></p>
                  <%end%>

                  <% if order_item.quantity>1 %>
                    <p> Price for <%= order_item.quantity %> pieces <%= order_item.total_price_item %>$
                  <% elsif order_item.quantity==1 %>
                    <p> Price for <%= order_item.quantity %> piece <%= order_item.total_price_item %>$
                  <% end %></p>
                </div>

                <div class="col-md-1 mt-2" >
                  <%= link_to "Destroy", order_item_path(order_item), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                                      }, class: 'btn bg-info rounded-0' %> 
                </div>
              </div>
            </div>
          </div> 
        <% end %>
      </div>
    
      <div class="col-md-3" >
        <p class="fw-bold text-end mx-5 my-3">Total price <%= current_order.total_price %> $ </p>

        <div class="d-flex justify-content-end mx-5">
          <% if current_order.order_items.size >= 1 && !@delivery.present?%>
            <p> <%= link_to "Place an order", new_delivery_path, class: 'btn btn-dark rounded-0'%> </p>
          <% elsif current_order.order_items.size >= 1 && @delivery.present?%>
            <p> <%= link_to "Place an order", order_verification_path, class: 'btn btn-dark rounded-0'%> </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>







                                      

app/views/order/show_order.html.erb
<div class="container-fluid">
  <div class="card border border-info rounded-0 mt-2">
    <div class="card-body px-5">
      <div class="row">
        <div class="col-md-4">
          <p> Status <%= @order.status %> </p>
          <p> Total price <%= @order.total_price %> $</p>
        </div>

        <div class="col-md-4">
          <p> Order number <%= @order.id %> </p>
          <p> Update date <%= @order.updated_at.strftime('%d-%m-%Y') %> </p>        
        </div>
      </div>
    </div>
  </div>  
      
  <% @order_items.each do |order_item| %>
    <div class="card border border-info rounded-0 mt-2">
      <div class="card-body px-5">
        <div class="row">
          <div class="col-md-4 mt-2">
            <% if order_item.mirror.mirror_images.attached?%>
              <%= image_tag order_item.mirror.mirror_images.first.variant(resize_to_limit: [218, 185]).processed  %>
            <% end%>       
          </div>

          <div class="col-md-4 mt-2" >
            <p> <%= order_item.mirror.name %> </p>
            <p> Height <%= order_item.height %> mm </p>
            <p> Width <%= order_item.width %> mm </p>
            <p> Glass thickness <%= order_item.glass_thickness %> mm </p>
            <p> <%= order_item.light.capitalize %> light  </p>
            <p> <%= order_item.heater == true ? "With heater" : "Without heater" %> </p>
          </div>

          <div class="col-md-3 mt-2" >
            <p> Unit price: <%= order_item.unit_price %> $</p>
            <p> Quantity: <%= order_item.quantity %> </p>
          </div>          
        </div>
      </div>
    </div>
  <% end %>
 
  <div class="card border border-info rounded-0 mt-2">
    <div class="card-body px-5">
      <div class="fw-bold text-end mx-3">Total price <%= current_order.total_price %>$</div>
      <div class="d-flex justify-content-end mx-3">
        <% if @order.status == 'in progress' %>
            <div> <%= link_to "Edit the order", order_path, class: 'btn bg-info rounded-0'%> </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card border border-info rounded-0 mt-2">
    <div class="card-body px-5">
      <% if @delivery.nil? %>
        <div class="fs-4">Delivery information missing</div>
      <% else %>
        <div class="fs-4">Delivery information</div>
        <% if @delivery.delivery_type == 'Delivery to the post office' %>
          <div>
            <%= @delivery.delivery_type %>
            <%= @delivery.post %>
            number <%= @delivery.post_office_number %>
            in <%= @delivery.city %>,
            <%= @delivery.region %> region
          </div>
          <div>
            Receiver:
            <%= @delivery.receiver_name %>
            <%= @delivery.receiver_surname %>
          </div>
          <div>
            Receiver phone number:
            <%= @delivery.receiver_phone_number %>
          </div>
        <% else %>
          <div>
            Delivery by
            <%= @delivery.post %>
            courier to the address of
            <%= @delivery.region %> region,
            <%= @delivery.city %>,
            <%= @delivery.receiver_address %>
          </div>
          <div>
            Receiver:
            <%= @delivery.receiver_name %>
            <%= @delivery.receiver_surname %>
          </div>
          <div>
            Receiver phone number:
            <%= @delivery.receiver_phone_number %>
          </div>
        <% end %>
        <% if @order.status == 'in progress' %>
          <div> <%= link_to "Edit the delivery information", edit_delivery_path(@order), class: 'btn bg-info rounded-0'%> </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
    
    