config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'mirrors#index'

  resources :mirrors, only: %i[show index] do
    resource :mirror_calculations, only: %i[show update]
  end

  resources :order_items
  resources :orders, only: %i[index show]
  resource :carts, only: %i[show edit update]
  resource :delivery, only: %i[new create edit update], path: '/order/delivery'
  resources :users, only: %i[new create]
  resource :user, only: %i[edit update]
  resource :session, only: %i[new create destroy]

  namespace :admin do
    resources :mirrors, except: %i[show index] do
      resource :mirror_images, only: [:destroy]
    end

    resources :users, only: %i[index show new create edit update]

    resources :order, only: %i[index show edit update] do
      resources :order_items, only: %i[edit update destroy]
      resource :delivery, only: %i[edit update]
    end

    resource :informations, only: %i[edit update]
  end

  get '/delivery_information', to: 'informations#delivery_information', as: :delivery_information
  get '/company_information', to: 'informations#company_information', as: :company_information
  get '/contact_information', to: 'informations#contact_information', as: :contact_information
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  include Authentication
  before_action :no_authentication

  def show
    @order_items = current_order.order_items.includes(mirror: [mirror_images_attachments: { blob: :variant_records }])

    @delivery = current_order.delivery
  end

  def edit
    if current_order.order_items.empty?
      redirect_to mirrors_path, flash: { warning: I18n.t('cart_is_empty') }
    else
      @order_items = current_order.order_items.includes(mirror: [mirror_images_attachments: { blob: :variant_records }])
      @delivery = current_order.delivery
    end
  end

  def update
    current_order.update(status: 'confirmed')
    session.delete(:order_id)
    redirect_to mirrors_path, flash: { success: I18n.t('thank_you_for_your_order') }
  end
end

app/views/carts/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9" >
      <% @order_items.each do |order_item| %>
        <div class="card border border-info border-top-0 rounded-0">
          <div class="card-body px-5">
            <div class="row">
              <div class="col-md-4 mt-2">
                <% if order_item.mirror.mirror_images.attached?%>
                  <%= image_tag order_item.mirror.mirror_images.first.variant(resize_to_limit: [300, 250]).processed  %>
                <% end%>
              </div>

              <div class="col-md-4 mt-2" >
                <p> <%= order_item.mirror.name %> </p>
                <p> Height <%= order_item.height %> mm </p>
                <p> Width <%= order_item.width %> mm </p>
                <p> Glass thickness <%= order_item.glass_thickness %> mm </p>
                <p> <%= order_item.light.capitalize %> light  </p>
                <p> <%= order_item.heater == true ? "With heater" : "Without heater" %> </p>
              </div>

              <div class="col-md-3 mt-2" >
                <p> Unit price: <%= order_item.unit_price %> $</p>
                <p> Quantity: <%= order_item.quantity %> </p>
              </div>
            </div>
          </div>
        </div>  
      <% end %>
    </div>
    
    <div class="col-md-3" >
      <p class="fw-bold text-end mx-5 my-3">Total price <%= current_order.total_price %>$</p>
               
      <div class="d-flex justify-content-end mx-5">
        <%= link_to "Edit the order", carts_path, class: 'btn bg-info rounded-0'%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <p class="fs-4"> Delivery information</p>

      <%if @delivery.delivery_type == 'Delivery to the post office'%>
        <p> <%= @delivery.delivery_type %> 
            <%= @delivery.post %>
            number <%= @delivery.post_office_number %>
            in <%= @delivery.city %>,
            <%= @delivery.region %> region
        </p>
        <p> Receiver:
          <%= @delivery.receiver_name %>
          <%= @delivery.receiver_surname %> 
        </p>
        <p> Receiver phone number:
          <%= @delivery.receiver_phone_number %> </p>
      <%else%>
        <p> Delivery by 
          <%= @delivery.post %> 
          courier to the address of
          <%= @delivery.region %> region, 
          <%= @delivery.city %>, 
          <%= @delivery.receiver_address %>  
        </p>
        <p> Receiver:
          <%= @delivery.receiver_name %>
          <%= @delivery.receiver_surname %> 
        </p>
        <p> Receiver phone number:
          <%= @delivery.receiver_phone_number %> </p>
      <% end %>

      <p> <%= link_to "Edit delivery information", edit_delivery_path, class: 'btn bg-info rounded-0'%> </p>
    </div>
    <div class="col-md-6">
      <p class="fs-4"> Buyer Information </p>
      <p> Buyer name:
      <%= @current_user.name %> </p>
      <p> Buyer phone number:
      <%= @current_user.phone_number %> </p>

      <p><%= link_to "Edit buyer information", edit_user_path(redirect: edit_carts_path), class: 'btn bg-info rounded-0' %></p>
    </div>
  </div>
 
    <p> <%= button_to 'Confirm the order', carts_path, method: :patch, class: 'btn btn-dark rounded-0' %> </p>
</div>

app/views/carts/show.html.erb
<div class="container-fluid">
  <% if @order_items.size == 0 %>
    <p class="fs-4"> Your cart is empty </p>
  <% else %>
    <div class="row">
      <div class="col-md-9" >
        <% @order_items.each do |order_item| %>
          <div class="card border border-info border-top-0 rounded-0">
            <div class="card-body px-5">
              <div class="row">
                <div class="col-md-4 mt-2">
                  <% if order_item.mirror.mirror_images.attached?%>
                    <%= image_tag order_item.mirror.mirror_images.first.variant(resize_to_limit: [300, 250]).processed  %>
                  <%end%>
                </div>

                <div class="col-md-3 mt-2" >
                  <p> <%= order_item.mirror.name %> </p>

                  <%= form_with model: order_item do |form| %>

                    <p><%= form.label :height %>
                    <%= form.select :height, [50, 80, 100], {}, { onchange: 'this.form.submit();' }  %> 
                    <%= form.submit type: :hidden %></p>

                    <p><%= form.label :width %>
                    <%= form.select :width, [50, 80], {}, { onchange: 'this.form.submit();' }  %> 
                    <%= form.submit type: :hidden %></p>

                    <p><%= form.label :glass_thickness %>
                    <%= form.select :glass_thickness, [4, 6], {}, { onchange: 'this.form.submit();' } %>
                    <%= form.submit type: :hidden %></p>

                    <p><%= form.label :light %> 
                    <%= form.select :light, ['warm', 'neutral', 'cold'], {}, { onchange: 'this.form.submit();' } %> 

                    <p><%= form.label :heater %>
                    <%= form.check_box :heater, { onchange: 'this.form.submit();' } %> 
                    <%= form.submit type: :hidden %></p>

                  <% end %>

                </div>

                <div class="col-md-4 mt-2" >
                  <%= form_with model: order_item do |form| %>
                    <p><%= form.hidden_field :mirror_id, value: order_item.mirror.id %> 
                    Quantity <%= form.number_field :quantity, in: 1.0..20.0, step: 1, value: order_item.quantity %>
                    <%= form.submit "Update", class: 'btn bg-info rounded-0' %></p>
                  <%end%>

                  <% if order_item.quantity>1 %>
                    <p> Price for <%= order_item.quantity %> pieces <%= order_item.total_price_item %>$
                  <% elsif order_item.quantity==1 %>
                    <p> Price for <%= order_item.quantity %> piece <%= order_item.total_price_item %>$
                  <% end %></p>
                </div>

                <div class="col-md-1 mt-2" >
                  <%= link_to "Destroy", order_item_path(order_item), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                                      }, class: 'btn bg-info rounded-0' %> 
                </div>
              </div>
            </div>
          </div> 
        <% end %>
      </div>
    
      <div class="col-md-3" >
        <p class="fw-bold text-end mx-5 my-3">Total price <%= current_order.total_price %> $ </p>

        <div class="d-flex justify-content-end mx-5">
          <% if @delivery.present?%>
            <p> <%= link_to "Place an order", edit_carts_path, class: 'btn btn-dark rounded-0'%> </p>
          <% else%>
             <p> <%= link_to "Place an order", new_delivery_path, class: 'btn btn-dark rounded-0'%> </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>    