config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'mirrors#index'

  resources :mirrors, only: %i[show index] do
    resource :mirror_calculations, only: %i[show update]
  end

  resources :order_items
  resources :orders, only: %i[index show]
  resource :carts, only: %i[show edit update]
  resource :delivery, only: %i[new create edit update], path: '/order/delivery'
  resources :users, only: %i[new create]
  resource :user, only: %i[edit update]
  resource :session, only: %i[new create destroy]

  namespace :admin do
    resources :mirrors, except: %i[show index] do
      resource :mirror_images, only: [:destroy]
    end

    resources :users, only: %i[index show new create edit update]

    resources :order, only: %i[index show edit update] do
      resources :order_items, only: %i[edit update destroy]
      resource :delivery, only: %i[edit update]
    end

    resource :informations, only: %i[edit update]
  end

  get '/delivery_information', to: 'informations#delivery_information', as: :delivery_information
  get '/company_information', to: 'informations#company_information', as: :company_information
  get '/contact_information', to: 'informations#contact_information', as: :contact_information
end

app/models/mirror.rb
# frozen_string_literal: true

class Mirror < ApplicationRecord
  include MirrorPriceCalculation

  has_many_attached :mirror_images
  has_many :order_items
  has_rich_text :description

  validates :name, presence: true

  validates :height, presence: true
  VALID_HEIGHT = [50, 80, 100].freeze
  validates :height, inclusion: { in: VALID_HEIGHT }

  validates :width, presence: true
  VALID_WIDTH = [50, 80].freeze
  validates :width, inclusion: { in: VALID_WIDTH }

  validates :glass_thickness, presence: true
  VALID_GLASS_THICKNESS = [4, 6].freeze
  validates :glass_thickness, inclusion: { in: VALID_GLASS_THICKNESS }

  VALID_LIGHT = %w[warm neutral cold].freeze
  validates :light, inclusion: { in: VALID_LIGHT }

  VALID_INSTALLATION = %w[wall table].freeze
  validates :installation, inclusion: { in: VALID_INSTALLATION }

  VALID_LAMP = %w[built-in outside].freeze
  validates :lamp, inclusion: { in: VALID_LAMP }

  validates :price_square, presence: true

  scope :filter_installation, ->(value) {
    if value == 'wall'
      where(installation: 'wall')
    elsif value == 'table'
      where(installation: 'table')
    else
      all
    end
  }
 
  scope :filter_lamp, ->(value) {
    if value == 'built-in'
      where(lamp: 'built-in')
    elsif value == 'outside'
      where(lamp: 'outside')
    else
      all
    end
  }
  scope :with_field_order, lambda { |field = nil, order = nil|
                             allowed_fields = ['price_square']
                             field = nil if allowed_fields.exclude?(field)

                             direction = order == 'desc' ? 'desc' : 'asc'

                             order(field => direction) if field
                           }
end

app/controllers/admin/mirrors_controller.rb
# frozen_string_literal: true

module Admin
  class MirrorsController < ApplicationController
    include Authentication
    include Admin::Concerns::AdminAuthentication

    before_action :no_authentication
    before_action :check_admin

    def new
      @mirror = Mirror.new
    end

    def create
      @mirror = Mirror.new(mirror_params)

      if @mirror.save
        redirect_to mirrors_path, flash: { success: I18n.t('mirror_created') }
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @mirror = Mirror.find(params[:id])
    end

    def update
      @mirror = Mirror.find(params[:id])

      if @mirror.update(mirror_params)
        redirect_to mirror_path(@mirror), flash: { success: I18n.t('mirror_updated') }
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @mirror = Mirror.find(params[:id])
      @mirror.destroy
      redirect_to mirrors_path, status: :see_other, flash: { success: I18n.t('mirror_deleted') }
    end

    private

    def mirror_params
      params.require(:mirror).permit(:name, :height, :width, :glass_thickness, :light, :heater, :price_square,
                                     :installation, :lamp, :description, mirror_images: [])
    end
  end
end

app/controllers/mirrors_controller.rb
# frozen_string_literal: true

class MirrorsController < ApplicationController
  def index
    @mirrors = Mirror.includes(mirror_images_attachments: { blob: :variant_records })
                     .filter_installation(params[:installation])
                     .filter_lamp(params[:lamp])
                     .with_field_order(*params[:order].to_s.split('-'))
  end

  def show
    @mirror = Mirror.find(params[:id])
    @order_items = current_order.order_items.new if current_user.present?
  end
end

app/views/mirrors/edit.html.erb
<%= link_to "All mirrors", mirrors_path %>
<h4>Edit</h4>

<%= form_with model: @mirror do |form| %>
  
<p><%= form.label :name %> 
<%= form.text_field :name %> </p>

<p><%= form.label :height %> 
<%= form.select :height, [50, 80, 100], {}, { onchange: 'this.form.submit();' }  %> 
<%= form.submit type: :hidden %></p>

<p><%= form.label :width %>
<%= form.select :width, [50, 80], {}, { onchange: 'this.form.submit();' }  %> 
<%= form.submit type: :hidden %></p>

<p><%= form.label :glass_thickness %>
<%= form.select :glass_thickness, [4, 6], {}, { onchange: 'this.form.submit();' } %>
<%= form.submit type: :hidden %></p>

<p><%= form.label :light %> 
<%= form.select :light, [ 'warm', 'neutral', 'cold' ] %> 

<p><%= form.label :heater %>
<%= form.check_box :heater, { onchange: 'this.form.submit();' } %> 
<%= form.submit type: :hidden %></p>

<p> <%= form.label :installation %>
<%= form.select :installation, [ 'wall', 'table' ] %> </p>

<p> <%= form.label :lamp %>
<%= form.select :lamp, [ 'built-in', 'outside' ]  %> </p>


<p><%= form.label :price_square %> 
<%= form.text_field :price_square %> $ per square meter </p>

<p> <%= form.label :mirror_images %> </p>

 <% if @mirror.mirror_images.attached?%>
          <%  @mirror.mirror_images.map do |mirror_image|%>
            <%=  image_tag mirror_image.variant(resize_to_limit: [218, 185]).processed %>
          <% end%>
        <% end%>
<p><%= form.file_field :mirror_images,  multiple: true, include_hidden: false %> </p>

<!-- <p>
  <%= form.label :mirror_images, "Add image", class: 'btn btn-outline-secondary text-black' %>
  <%= form.file_field :mirror_images, multiple: true, style: 'display: none', id: 'mirror_images_field' %>
</p> -->

<p><% if @mirror.mirror_images.attached?%>
 <%= link_to "Remove images", mirror_mirror_images_path(@mirror), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?" 
                                      }, class: 'btn btn-outline-secondary text-black' %> 
                                      
                    <% end%> </p>



<%= form.submit "Update", class: 'btn bg-success text-black' %>

<% end %>


<p>Price <%= @mirror.price %>

app/views/mirrors/index.html.erb
<div class="container-fluid">

  <div class="row">

    <div class="col-md-2 border border-info border-top-0 mt-2" >
      
      <%= form_with(url: mirrors_path, method: 'get') do |form| %>
        <div class="border-bottom border-info">
          <p>Installation</p>
       
          <p><%= form.radio_button :installation, '', onchange: 'this.form.submit();' %> 
          <%= form.label :installation, 'All'%></p>

          <p><%= form.radio_button :installation, 'wall', checked: params[:installation] == 'wall', onchange: 'this.form.submit();' %>
          <%= form.label :installation, "Wall" %></p>

          <p><%= form.radio_button :installation, 'table', checked: params[:installation] == 'table', onchange: 'this.form.submit();' %>
          <%= form.label :installation, "Table" %></p>
        </div>

        <div class="border-bottom border-info">
          <p>Lamp</p>

          <p><%= form.radio_button :lamp, '', onchange: 'this.form.submit();' %> 
          <%= form.label :lamp, 'All'%></p>

          <p><%= form.radio_button :lamp, 'built-in', checked: params[:lamp] == 'built-in', onchange: 'this.form.submit();' %>
          <%= form.label :lamp, "Built-in" %></p>

          <p><%= form.radio_button :lamp, 'outside', checked: params[:lamp] == 'outside', onchange: 'this.form.submit();' %>
          <%= form.label :lamp, "Outside" %></p>
        </div>

        <div class="border-bottom border-info">
          <p>Sort by</p>

          <p><%= form.radio_button :order, '', checked: params[:order] == '', onchange: 'this.form.submit();' %> 
          <%= form.label :order, 'Recommended'%></p>
     
          <p><%= form.radio_button :order, 'price_square-desc', checked: params[:order] == 'price_square-desc', onchange: 'this.form.submit();' %> 
          <%= form.label :order, 'Price (High-Low)'%></p>

          <p><%= form.radio_button :order, 'price_square-asc', checked: params[:order] == 'price_square-asc', onchange: 'this.form.submit();' %> 
          <%= form.label :order, 'Price (Low-High)'%></p>
        </div>

      <% end %>
    </div>

    <div class="col-md-10 mt-2">
      <div class="row">
        <% @mirrors.each do |mirror| %>
          <div class="col-lg-4 col-md-6 col-12 mb-4">
            <div class="card border border-info rounded-0">
              <div class="card-body px-5">
                <h5><%= link_to "#{mirror.name}", mirror_path(mirror), class: 'nav-link ' %></h5>

                <p>from <%= (mirror.price_square*0.25).round %>$</p>

                <% if mirror.mirror_images.attached? %>
                  <%  mirror.mirror_images.map do |mirror_image|%>
                    <%= link_to mirror_path(mirror) do %>
                      <%=  image_tag mirror_image.variant(resize_to_limit: [300, 250]).processed %>
                    <% end%>
                  <% end%>
                <% end%>

                <% if current_user.present? && current_user.admin?%>
                  <p><%= link_to "Edit", edit_admin_mirror_path(mirror), class: 'btn bg-info rounded-0' %>
                     <%= link_to "Destroy", admin_mirror_path(mirror), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"}, class: 'btn bg-warning-subtle rounded-0' %> </p>
                <% end %>
                             
              </div>
            </div>
          </div>
        <% end %>
	    </div>
    </div>
  </div>
</div>

 

app/views/mirrors/new.html.erb
<h4>New</h4>

<%= form_with model: @mirror do |form| %>
  
<p> <%= form.label :name %> 
<%= form.text_field :name %> </p>

<p> <%= form.label :height %> 
<%= form.select :height, [50, 80, 100] %> </p>

<p> <%= form.label :width %> 
<%= form.select :width, [50, 80]  %> </p>

<p> <%= form.label :glass_thickness %> 
<%= form.select :glass_thickness, [4, 6] %> </p>

<p> <%= form.label :light %> 
<%= form.select :light, [ 'warm', 'neutral', 'cold' ] %> </p>

<p> <%= form.label :heater %>
<%= form.check_box :heater %> </p>

<p> <%= form.label :installation %>
<%= form.select :installation, [ 'wall', 'table' ] %> </p>

<p> <%= form.label :lamp %>
<%= form.select :lamp, [ 'built-in', 'outside' ]  %> </p>

<p> <%= form.label :price_square %> 
<%= form.text_field :price_square %> </p>

<p> <%= form.label :mirror_images %> </p>
<p><%= form.file_field :mirror_images, multiple: true %> </p>

<%= form.submit "Create", class: 'btn bg-success text-black' %>

<% end %>

app/views/mirrors/show.html.erb
<div class="container-fluid">
  <% if current_user.present? && current_user.admin?%>
    <%= link_to "Edit", edit_admin_mirror_path(@mirror), class: 'btn bg-info rounded-0'%>
    <%= link_to "Destroy", admin_mirror_path(@mirror), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"}, class: 'btn bg-warning-subtle rounded-0'%>
  <%end%>

  <div class="row">
    <div class="col-md-6 border border-info border-top-0 mt-2" >
      <p> <% if @mirror.mirror_images.attached?%>
        <% @mirror.mirror_images.each do |mirror_image| %>
          <%= image_tag mirror_image %>
        <%end%>
      <%end%> </p>
      <div class="row">
        <div class="col-md-6">
          <p class="fs-4"> <%= @mirror.name %> </p>
          <p class="fw-bold"> Price from
            <%= (@mirror.price_square*0.25).round %>$</p>
          <p><%= link_to "Price calculator", mirror_mirror_calculations_path(@mirror), class: 'btn bg-info rounded-0' %></p>
        </div>
        <div class="col-md-6">
          <% if current_user.present? %>
            <%= form_with model: @order_items do |form| %>
              <p><%= form.hidden_field :mirror_id, value: @mirror.id %> 
              <%= form.number_field :quantity, in: 1.0..20.0, step: 1, value: 1  %>
              <%= form.submit "Add to cart", class: 'btn bg-info rounded-0'%></p>
            <%end%>
          <% else %>
            <p><%= link_to "Sign up to add to cart", new_user_path, class: 'btn bg-info rounded-0' %></p>
            <p><%= link_to "Log in to add to cart", new_session_path, class: 'btn bg-info rounded-0' %></p>
          <%end%>
        </div>
      </div>
    </div>

    <div class="col-md-6 border border-info border-top-0 border-left-0 mt-2" >
      <p> <%= @mirror.description %> </p>
    </div>
  </div>
</div>