config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'mirrors#index'

  resources :mirrors, only: %i[show index] do
    resource :mirror_calculations, only: %i[show update]
  end

  resources :order_items
  resources :orders, only: %i[index show]
  resource :carts, only: %i[show edit update]
  resource :delivery, only: %i[new create edit update], path: '/order/delivery'
  resources :users, only: %i[new create]
  resource :user, only: %i[edit update]
  resource :session, only: %i[new create destroy]

  namespace :admin do
    resources :mirrors, except: %i[show index] do
      resource :mirror_images, only: [:destroy]
    end

    resources :users, only: %i[index show new create edit update]

    resources :order, only: %i[index show edit update] do
      resources :order_items, only: %i[edit update destroy]
      resource :delivery, only: %i[edit update]
    end

    resource :informations, only: %i[edit update]
  end

  get '/delivery_information', to: 'informations#delivery_information', as: :delivery_information
  get '/company_information', to: 'informations#company_information', as: :company_information
  get '/contact_information', to: 'informations#contact_information', as: :contact_information
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :orders

  before_save :capitalize_name

  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true, format: { with: /\A\+\d+\z/ }, length: { is: 13 }
  validates :password, confirmation: true, length: { minimum: 8, maximum: 70 }, if: :password_validation_required?
  validates :password_confirmation, presence: true, if: :password_digest_changed?
  validates :name, presence: true, length: { minimum: 2, maximum: 40 }

  scope :filter_phone_number, ->(value) { where(phone_number: value) unless value.blank? }

  scope :filter_status, ->(value) {
  if value == '1'
    where(admin: true)
  elsif value == '0'
    where(admin: false)
  else
    all
  end
}


  private

  def password_validation_required?
    new_record? || password_digest_changed?
  end

  def capitalize_name
    self.name = name.capitalize
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    include Admin::Concerns::AdminAuthentication

    before_action :check_admin

    def index
      @users = User.filter_phone_number(params[:phone_number])
                   .filter_status(params[:admin])
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def create
      create_user

      if @user.valid?
        redirect_to mirrors_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to admin_user_path(@user)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def create_user
      @user = User.create(user_params)
    end

    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :phone_number, :admin)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Authentication

  before_action :authentication, only: %i[new create]
  before_action :no_authentication, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    create_user
    session[:user_id] = @user.id

    if @user.valid?
      redirect_to mirrors_path, flash: { success: I18n.t('welcome_user', name: @user.name) }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to(params[:redirect] || mirrors_path, flash: { success: I18n.t('your_profile_was_updated') })
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def create_user
    @user = User.create(user_params)
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :phone_number)
  end
end

app/views/admin/users/edit.html.erb
<div class="container mx-3">
  <p class="fs-4 mt-2">Edit the user infotrmation</p>

  <p> ID: <%= @user.id %> </p>
  <p> Phone number: <%= @user.phone_number %> </p>
  <p> Name: <%= @user.name %> </p>
  <p> Email: <%= @user.email %> </p>

  <% unless @current_user == @user%>
    <%= form_with model: [:admin, @user] do |form| %>
      <p> <%= form.label :admin %>
      <%= form.check_box :admin, checked: @user.admin? %> </p>
      <%= form.submit "Update the user infotrmation", class: 'btn bg-info rounded-0' %>
    <% end %>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2 border border-info border-top-0 mt-2">
      <%= form_with(url: admin_users_path, method: 'get') do |form| %>
        <div class="border-bottom border-info">
          <p>Status</p>

          <p><%= form.radio_button :admin, '', onchange: 'this.form.submit();' %> 
          <%= form.label :admin, 'All'%></p>

          <p><%= form.radio_button :admin, '1', checked: params[:admin] == '1', onchange: 'this.form.submit();' %>
          <%= form.label :admin, "Admin" %></p>

          <p><%= form.radio_button :admin, '0', checked: params[:admin] == '0', onchange: 'this.form.submit();' %>
          <%= form.label :admin, "User" %></p>
        </div>

        <div class="border-bottom border-info mt-3">
          <p><%= form.text_field :phone_number, placeholder: 'Enter phone number' %></p>
          <p><%= form.submit 'Search', class: 'btn bg-info rounded-0' %></p>
        </div>        
      <% end %>
    </div>

    <div class="col-md-10 mt-2">
      <table class="table table-bordered border-info">
        <thead>
          <tr>
            <th>Phone number</th>
            <th>User name</th>
            <th>The right of administration</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.phone_number %></td>
              <td><%= user.name %></td>
              <td><%= user.admin %></td>                
              <td><%= link_to 'The user information', admin_user_path(user), class: 'btn bg-info rounded-0' %></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container mx-3">
  <p class="fs-4 mt-2">Create a new user</p>

  <%= form_with model: [:admin, @user] do |form| %>
    <div class="row">
      <div class="col-md-6">
        <p> <%= form.label :email %> 
        <%= form.email_field :email, class: 'form-control' %>
        <% @user.errors.full_messages_for(:email).each do |message|  %>
          <div class="text-danger"><%= message %></div>
        <% end %> </p>

        <p> <%= form.label :name %> 
        <%= form.text_field :name, class: 'form-control' %> 
        <% @user.errors.full_messages_for(:name).each do |message|  %>
          <div class="text-danger"><%= message %></div>
        <% end %> </p>

        <p> <%= form.label :phone_number %> 
        <%= form.text_field :phone_number, placeholder: '+380 xxx xx xx xx', class: 'form-control' %> 
        <% @user.errors.full_messages_for(:phone_number).each do |message|  %>
          <div class="text-danger"><%= message %></div>
        <% end %> </p>

        <p> <%= form.label :password %> 
        <%= form.password_field :password, class: 'form-control'  %> 
        <% @user.errors.full_messages_for(:password).each do |message|  %>
          <div class="text-danger"><%= message %></div>
        <% end %> </p>

        <p> <%= form.label :password_confirmation %> 
        <%= form.password_field :password_confirmation, class: 'form-control' %> </p>
        <p> <% @user.errors.full_messages_for(:password_confirmation).each do |message|  %>
          <div class="text-danger"><%= message %></div>
        <% end %> </p>

        <p> <%= form.label :admin %>
        <%= form.check_box :admin %> </p>

        <%= form.submit "Sign up", class: 'btn bg-info rounded-0' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container-fluid">
  <div class="card border border-info rounded-0 mt-2">
    <div class="card-body px-5">
      <div class="row">
        <div class="col-md-4">
          <% unless @current_user == @user%>
            <% if @user.admin %>
              <p><%= link_to 'Remove administrator rights', edit_admin_user_path(@user), class: 'btn bg-info rounded-0'  %> </p>
            <% else %>
              <p><%= link_to 'Grant administrator rights', edit_admin_user_path(@user), class: 'btn bg-info rounded-0'  %> </p>
            <% end %>
          <% end %>

          <p>ID: <%= @user.id %> </p>
          <p>The right of administration: <%= @user.admin %> </p>
        </div>
        <div class="col-md-4">
          <p>Phone number: <%= @user.phone_number %> </p>
          <p>Name: <%= @user.name %> </p>
          <p>Email: <%= @user.email %> </p>
        </div>
      </div>
    </div>
  </div>

  <table class="table table-bordered border-info mt-2">
    <thead>
      <tr>
        <th>Order id</th>
        <th>Status</th>
        <th>Total price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @user.orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.status %></td>
          <td><%= order.total_price %> $</td>                
          <td><%= link_to 'The order information', edit_admin_order_path(order), class: 'btn bg-info rounded-0' %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>




          